Repository xai4space/meteors, pull requests merged in 2024-10, with the labels that each got.

#92 fix: 91 docs the lime illustration image is missing in the docs
  .pre-commit-config.yaml
  docs/assets/UML_diagram.png
  examples/lime/lime.ipynb
  pyproject.toml
Labels: fix :medical_symbol:

#94 chore: reduced coverage treshold
  .codecov.yaml
Labels: chore :bellhop_bell:

#93 fix: Updated occlusion
  src/meteors/attr/occlusion.py
  tests/attr/test_attribution_methods.py
Labels: fix :medical_symbol:

#101 feat: Custom errors
  examples/lime/lime.ipynb
  src/meteors/attr/attributes.py
  src/meteors/attr/explainer.py
  src/meteors/attr/hyper_noise_tunnel.py
  src/meteors/attr/input_x_gradients.py
  src/meteors/attr/integrated_gradients.py
  src/meteors/attr/lime.py
  src/meteors/attr/noise_tunnel.py
  src/meteors/attr/occlusion.py
  src/meteors/attr/saliency.py
  src/meteors/exceptions/__init__.py
  src/meteors/exceptions/exceptions.py
  src/meteors/hsi.py
  src/meteors/utils/utils.py
  src/meteors/visualize/hsi_visualize.py
  src/meteors/visualize/lime_visualize.py
  tests/attr/test_attributes.py
  tests/attr/test_attribution_methods.py
  tests/attr/test_explainer.py
  tests/attr/test_hyper_noise_tunnel.py
  tests/attr/test_lime.py
  tests/test_hsi.py
  tests/utils/utils/test_utils.py
  tests/visualize/test_hsi_visualize.py
  tests/visualize/test_lime_visualize.py
Labels: enhancement :hammer:

#107 feat: 105 feat aggregation for segmentation integrated into explainer object
  src/meteors/attr/explainer.py
  src/meteors/attr/input_x_gradients.py
  src/meteors/attr/integrated_gradients.py
  src/meteors/attr/lime.py
  src/meteors/attr/lime_base.py
  src/meteors/attr/noise_tunnel.py
  src/meteors/attr/occlusion.py
  src/meteors/attr/saliency.py
  src/meteors/utils/utils.py
  tests/attr/test_attribution_methods.py
  tests/attr/test_explainer.py
  tests/attr/test_lime.py
  tests/attr/test_noise_tunnel.py
  tests/utils/utils/test_utils.py
Labels: enhancement :hammer:

#110 feat: backbone class for HyperNoiseTunnel and NoiseTunnel
  docs/reference.md
  src/meteors/attr/noise_tunnel.py
  tests/attr/test_noise_tunnel.py
Labels: enhancement :hammer:

#111 feat: refactored the package structure
  examples/lime/lime.ipynb
  examples/lime/segmentation.ipynb
  src/meteors/__init__.py
  src/meteors/attr/explainer.py
  src/meteors/attr/input_x_gradients.py
  src/meteors/attr/integrated_gradients.py
  src/meteors/attr/lime.py
  src/meteors/attr/lime_base.py
  src/meteors/attr/occlusion.py
  src/meteors/attr/saliency.py
  src/meteors/exceptions.py
  src/meteors/exceptions/__init__.py
  src/meteors/models/__init__.py
  src/meteors/models/abstract.py
  src/meteors/models/linear.py
  src/meteors/utils.py
  src/meteors/utils/__init__.py
  src/meteors/visualize/lime_visualize.py
  tests/attr/test_attribution_methods.py
  tests/attr/test_explainer.py
  tests/attr/test_hyper_noise_tunnel.py
  tests/attr/test_lime.py
  tests/models/test_models.py
  tests/test_utils.py
  tests/visualize/test_attr_visualize.py
Labels: enhancement :hammer:

#103 feat: 96 feat segmentation support for attribution methods
  .gitignore
  .pre-commit-config.yaml
  docs/reference.md
  src/meteors/attr/__init__.py
  src/meteors/attr/explainer.py
  src/meteors/attr/hyper_noise_tunnel.py
  src/meteors/attr/input_x_gradients.py
  src/meteors/attr/integrated_gradients.py
  src/meteors/attr/lime.py
  src/meteors/attr/lime_base.py
  src/meteors/attr/noise_tunnel.py
  src/meteors/attr/occlusion.py
  src/meteors/attr/saliency.py
  src/meteors/utils.py
  tests/attr/test_attribution_methods.py
  tests/attr/test_explainer.py
  tests/attr/test_hyper_noise_tunnel.py
  tests/attr/test_lime.py
  tests/attr/test_noise_tunnel.py
  tests/test_utils.py
Labels: enhancement :hammer:

#112 chore: update the project version
  pyproject.toml
Labels: chore :bellhop_bell:

#116 fix: changelog.md and release notes do not contain all commits due to the commit processor not parsing multi-line commit messages.
  changelog.md
  commit_processor.py
Labels: fix :medical_symbol:
