Repository xai4space/meteors, pull requests merged in 2024-09, with the labels that each got.

#53 feat: Change orientation method
  src/meteors/image.py
  tests/test_image.py
Labels: enhancement :hammer:

#62 fix: Ingored dask warning
  src/meteors/image.py
  src/meteors/lime.py
Labels: fix :medical_symbol:

#61 fix: Changed from Image to HSI
  docs/reference.md
  pyproject.toml
  src/meteors/__init__.py
  src/meteors/hsi.py
  src/meteors/lime.py
  src/meteors/visualize/lime_visualize.py
  tests/test_hsi.py
  tests/test_lime.py
  tests/test_lime_visualise.py
  tests/test_models.py
Labels: fix :medical_symbol:

#59 feat: lime segmentation support
  pyproject.toml
  src/meteors/hsi.py
  src/meteors/lime.py
  src/meteors/lime_base.py
  src/meteors/utils/models/models.py
  src/meteors/utils/utils.py
  tests/test_hsi.py
  tests/test_lime.py
  tests/test_lime_visualise.py
  tests/test_models.py
  tests/test_utils.py
Labels: enhancement :hammer:

#68 fix: 60 bug when all attributes are equal to 0 the vizualizations fail
  pyproject.toml
  src/meteors/hsi.py
  src/meteors/lime.py
  src/meteors/visualize/lime_visualize.py
  tests/test_hsi.py
  tests/test_lime.py
  tests/test_lime_visualise.py
  tests/test_models.py
Labels: fix :medical_symbol:

#72 fix: Corrected visualizer aggregations
  src/meteors/lime.py
  src/meteors/utils/utils.py
  src/meteors/visualize/__init__.py
  src/meteors/visualize/lime_visualize.py
  tests/test_lime.py
  tests/test_lime_visualise.py
  tests/test_utils.py
Labels: fix :medical_symbol:

#73 feat: New release action added
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  changelog.md
  commit_processor.py
  pyproject.toml
  tests/test_commit_processor.py
Labels: enhancement :hammer:

#77 fix: add rotation change to the HSI image visualization
  src/meteors/visualize/lime_visualize.py
Labels: fix :medical_symbol:

#80 fix: changed templates
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: fix :medical_symbol:

#76 docs: New docs added
  .github/CODE_OF_CONDUCT.md
  .github/workflows/docs.yml
  README.md
  changelog.md
  docs/how-to-guides.md
  docs/quickstart.md
  docs/reference.md
  docs/tutorials/introduction.md
  examples/lime/lime.ipynb
  mkdocs.yml
  pyproject.toml
  src/meteors/hsi.py
  src/meteors/lime.py
Labels: documentation :books:

#79 fix: band mask generation with bands outside the HSI wavelength range
  src/meteors/lime.py
  src/meteors/visualize/__init__.py
  src/meteors/visualize/lime_visualize.py
  tests/test_lime.py
  tests/test_lime_visualise.py
Labels: fix :medical_symbol:

#83 fix: github action release workflow to pypi
  .github/workflows/release.yml
  pyproject.toml
Labels: fix :medical_symbol:

#51 feat: HyperNoiseTunnel and captum attribution methods
  assets/UML-attribution-methods.png
  changelog.md
  docs/reference.md
  examples/lime/lime.ipynb
  pyproject.toml
  src/meteors/__init__.py
  src/meteors/attr/__init__.py
  src/meteors/attr/attributes.py
  src/meteors/attr/explainer.py
  src/meteors/attr/hyper_noise_tunnel.py
  src/meteors/attr/input_x_gradients.py
  src/meteors/attr/integrated_gradients.py
  src/meteors/attr/lime.py
  src/meteors/attr/lime_base.py
  src/meteors/attr/noise_tunnel.py
  src/meteors/attr/occlusion.py
  src/meteors/attr/saliency.py
  src/meteors/hsi.py
  src/meteors/utils/__init__.py
  src/meteors/visualize/__init__.py
  src/meteors/visualize/attr_visualize.py
  src/meteors/visualize/hsi_visualize.py
  src/meteors/visualize/lime_visualize.py
  tests/attr/test_attributes.py
  tests/attr/test_attribution_methods.py
  tests/attr/test_explainer.py
  tests/attr/test_hyper_noise_tunnel.py
  tests/attr/test_lime.py
  tests/test_hsi.py
  tests/utils/models/test_models.py
  tests/utils/utils/test_utils.py
  tests/visualize/test_attr_visualize.py
  tests/visualize/test_hsi_visualize.py
  tests/visualize/test_lime_visualize.py
Labels: enhancement :hammer:

#87 fix: infinite loop in segmentation
  src/meteors/utils/utils.py
Labels: fix :medical_symbol:

#86 docs: fixed docs with reference
  .github/workflows/docs.yml
  .pre-commit-config.yaml
  .prettierignore
  docs/reference.md
  examples/lime/assets/lime_introduction.png
  examples/lime/lime.ipynb
  pyproject.toml
  src/meteors/attr/attributes.py
  src/meteors/attr/hyper_noise_tunnel.py
  src/meteors/attr/input_x_gradients.py
  src/meteors/attr/integrated_gradients.py
  src/meteors/attr/lime.py
  src/meteors/attr/noise_tunnel.py
  src/meteors/attr/occlusion.py
  src/meteors/attr/saliency.py
  src/meteors/visualize/attr_visualize.py
Labels: documentation :books:

#88 fix: segmentation issue for spectral segmentation problem
  .gitignore
  examples/lime/cloudsen12_models/__init__.py
  examples/lime/cloudsen12_models/cloudsen12.py
  examples/lime/cloudsen12_models/utils_torch.py
  examples/lime/segmentation.ipynb
  src/meteors/attr/lime.py
  src/meteors/utils/utils.py
  tests/utils/utils/test_utils.py
Labels: fix :medical_symbol:
