Repository xai4space/meteors, pull requests merged in 2024-11, with the labels that each got.

#117 fix: Corrected Attributes Functionalities
  src/meteors/attr/integrated_gradients.py
  src/meteors/attr/noise_tunnel.py
  src/meteors/attr/occlusion.py
  tests/attr/test_attribution_methods.py
  tests/attr/test_noise_tunnel.py
Labels: fix :medical_symbol:

#118 fix: Corrected visualisers
  src/meteors/hsi.py
  src/meteors/visualize/__init__.py
  src/meteors/visualize/attr_visualize.py
  src/meteors/visualize/hsi_visualize.py
  src/meteors/visualize/lime_visualize.py
  tests/visualize/test_attr_visualize.py
  tests/visualize/test_hsi_visualize.py
  tests/visualize/test_lime_visualize.py
Labels: fix :medical_symbol:

#119 feat: Updated release and docs GitHub actions to tigger when GitHub tag is pushed
  .github/workflows/docs.yml
  .github/workflows/release.yml
Labels: enhancement :hammer:

#123 fix: Moved the postprocessing to the ExplainableModel
  src/meteors/attr/explainer.py
  src/meteors/attr/input_x_gradients.py
  src/meteors/attr/integrated_gradients.py
  src/meteors/attr/lime.py
  src/meteors/attr/noise_tunnel.py
  src/meteors/attr/occlusion.py
  src/meteors/attr/saliency.py
  src/meteors/models/abstract.py
  tests/attr/test_attribution_methods.py
  tests/attr/test_explainer.py
  tests/attr/test_lime.py
  tests/attr/test_noise_tunnel.py
  tests/models/test_models.py
Labels: fix :medical_symbol:

#130 chore: update package version
  pyproject.toml
  requirements-docs.txt
Labels: chore :bellhop_bell:

#132 docs: fix navbar for new tutorials
  .github/workflows/docs.yml
  mkdocs.yml
Labels: documentation :books:

#133 docs: fix reference docs for visualizer modules
  docs/reference.md
Labels: documentation :books:

#136 feat: Added Hyperlinks to the PR in changelog
  commit_processor.py
  tests/test_commit_processor.py
Labels: enhancement :hammer:

#135 docs: fixed documentation versioning
  .github/workflows/docs.yml
  mkdocs.yml
Labels: documentation :books:

#129 docs: tutorials fixes
  README.md
  docs/how-to-guides.md
  docs/reference.md
  docs/tutorials/introduction.md
  examples/hyperview_challenge/attr_showcase.ipynb
  examples/hyperview_challenge/lime.ipynb
  examples/segmentation/data/wavelenghts.txt
  examples/segmentation/segmentation.ipynb
  src/meteors/attr/noise_tunnel.py
  src/meteors/visualize/hsi_visualize.py
Labels: documentation :books:

#142 chore: update the package version
  pyproject.toml
Labels: chore :bellhop_bell:

#145 feat: Updating Rye and preparing for shifting to uv
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  changelog.md
Labels: enhancement :hammer:

#138 feat: added option for title in the charts
  src/meteors/visualize/attr_visualize.py
  src/meteors/visualize/hsi_visualize.py
  tests/visualize/test_attr_visualize.py
  tests/visualize/test_hsi_visualize.py
Labels: enhancement :hammer:

#148 feat: Added internal batch size to Integrated Gradients
  src/meteors/attr/integrated_gradients.py
  src/meteors/visualize/hsi_visualize.py
  tests/attr/test_attribution_methods.py
Labels: enhancement :hammer:
