Repository xai4space/meteors, pull requests merged in 2024-07, with the labels that each got.

#23 feat: 16 naming conventions
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  .github/workflows/pr.yml
  requirements-dev.lock
  requirements.lock
Labels: enhancement :hammer:

#19 docs: Resolved github action docs errors
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  examples/lime.ipynb
  mkdocs.yml
  pyproject.toml
  requirements-dev.lock
  requirements-docs.txt
Labels: documentation :books:

#34 feat: Changed feature to feat
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement :hammer:

#37 docs: added logo as requested in #36
  README.md
  logo.png
Labels: documentation, documentation :books:

#38 docs: 36 logo
  .github/workflows/docs.yml
  README.md
  assets/logo.png
  mkdocs.yml
Labels: documentation :books:

#39 feat: Divided ci into test and lint
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .gitignore
  requirements-dev.lock
  requirements.lock
Labels: enhancement :hammer:

#22 feat: band mask created by hand
  pyproject.toml
  src/meteors/__init__.py
  src/meteors/lime.py
  src/meteors/visualise/__init__.py
  tests/test_band_mask.py
  tests/test_lime.py
Labels: enhancement :hammer:
