Repository xai4space/meteors, pull requests merged in 2024-12, with the labels that each got.

#149 docs: changes to the HYPERVIEW tutorial
  examples/hyperview_challenge/attr_showcase.ipynb
Labels: documentation :books:

#146 feat: Added band specific spatial attribution visualisation
  examples/hyperview_challenge/attr_showcase.ipynb
  examples/hyperview_challenge/lime.ipynb
  src/meteors/attr/attributes.py
  src/meteors/visualize/__init__.py
  src/meteors/visualize/attr_visualize.py
  tests/attr/test_attributes.py
  tests/attr/test_attribution_methods.py
  tests/models/test_models.py
  tests/visualize/test_attr_visualize.py
Labels: enhancement :hammer:

#151 fix: Set the keep_gradient argument to False in methods that can store the gradient in the final results
  examples/hyperview_challenge/attr_showcase.ipynb
  src/meteors/attr/input_x_gradients.py
  src/meteors/attr/integrated_gradients.py
  src/meteors/attr/noise_tunnel.py
  tests/attr/test_attribution_methods.py
  tests/attr/test_noise_tunnel.py
Labels: fix :medical_symbol:

#153 docs: changes to the segmentation tutorial
  examples/segmentation/segmentation.ipynb
Labels: documentation :books:

#154 docs: fixing a minor typo in readme
  README.md
Labels: documentation :books:

#152 docs: changes to the HYPERVIEW tutorial (LIME)
  examples/hyperview_challenge/lime.ipynb
  mkdocs.yml
Labels: documentation :books:

#127 docs: added citation file
  CITATION.cff
Labels: documentation :books:

#155 feat: standardize relative imports across codebase
  src/meteors/attr/explainer.py
  src/meteors/attr/input_x_gradients.py
  src/meteors/attr/integrated_gradients.py
  src/meteors/attr/lime.py
  src/meteors/attr/noise_tunnel.py
  src/meteors/attr/occlusion.py
  src/meteors/attr/saliency.py
Labels: enhancement :hammer:

#157 fix: Consistency of terminology for Attributes
  docs/reference.md
  src/meteors/attr/__init__.py
  src/meteors/attr/attributes.py
  src/meteors/attr/lime.py
  src/meteors/attr/occlusion.py
  src/meteors/visualize/attr_visualize.py
  tests/attr/test_attributes.py
  tests/attr/test_attribution_methods.py
  tests/attr/test_lime.py
  tests/visualize/test_attr_visualize.py
  tests/visualize/test_hsi_visualize.py
Labels: fix :medical_symbol:

#158 chore: bump up the package version
  pyproject.toml
Labels: chore :bellhop_bell:

#102 feat: HyperSHAP
  .pre-commit-config.yaml
  README.md
  changelog.md
  docs/reference.md
  pyproject.toml
  src/meteors/__init__.py
  src/meteors/attr/attributes.py
  src/meteors/shap/__init__.py
  src/meteors/shap/explainer.py
  src/meteors/shap/shap.py
  src/meteors/visualize/__init__.py
  src/meteors/visualize/attr_visualize.py
  src/meteors/visualize/shap_visualize.py
  tests/shap/test_shap.py
  tests/shap/test_shap_explainer.py
  tests/visualize/test_shap_visualize.py
Labels: enhancement :hammer:

#162 fix: update error and logging messages to use format method for consistency
  examples/hyperview_challenge/clip_utils.py
  examples/segmentation/cloudsen12_models/cloudsen12.py
  examples/segmentation/cloudsen12_models/utils_torch.py
  src/meteors/attr/attributes.py
  src/meteors/attr/explainer.py
  src/meteors/attr/input_x_gradients.py
  src/meteors/attr/integrated_gradients.py
  src/meteors/attr/lime.py
  src/meteors/attr/noise_tunnel.py
  src/meteors/attr/occlusion.py
  src/meteors/attr/saliency.py
  src/meteors/hsi.py
  src/meteors/models/abstract.py
  src/meteors/models/linear.py
  src/meteors/shap/explainer.py
  src/meteors/shap/shap.py
  src/meteors/utils.py
  src/meteors/visualize/attr_visualize.py
  src/meteors/visualize/shap_visualize.py
  tests/attr/test_explainer.py
  tests/attr/test_noise_tunnel.py
  tests/test_hsi.py
Labels: fix :medical_symbol:
